apiVersion: v2
name: galust-ai-layer
description: Galust AI layer umbrella chart for Kubernetes clusters
type: application
version: 0.1.2
appVersion: "0.1.2"

dependencies:
  - name: strapi
    alias: backend
    version: 18.9.0
    repository: oci://oci.trueforge.org/truecharts
    condition: backend.enabled
  - name: base
    alias: mcp
    version: 0.3.30
    repository: https://dasmeta.github.io/helm
    condition: mcp.enabled
  - name: base
    alias: mcpUseCase
    version: 0.3.30
    repository: https://dasmeta.github.io/helm
    condition: mcpUseCase.enabled
  - name: base
    alias: mcpProducts
    version: 0.3.30
    repository: https://dasmeta.github.io/helm
    condition: mcpProducts.enabled
  - name: base
    alias: orchestrator
    version: 0.3.30
    repository: https://dasmeta.github.io/helm
    condition: orchestrator.enabled
