# helm diff upgrade --install -n default with-secret-or-config-map-as-mounted-volume ./charts/base/ -f ./examples/base/with-secret-or-config-map-as-mounted-volume.yaml

image:
  repository: mendhak/http-https-echo
  tag: 34

containerPort: 8080

configs:
  ENV_VARIABLE_CONFIG: "8" # standard env variable
  /app/config-file4.txt: "content of /app/config-file4.txt" # single file mount, useful in case we mount to application existing internal folder
  /app/config1/: # folder with its files to mount to main container
    file1.txt: |
      file multi 
      line content 11
    file2.txt: |
      file multi 
      line content 12
  /app/config2/:
    file1.txt: |
      file multi 
      line content 21
    file2.txt: |
      file multi 
      line content 22

secrets:
  - ENV_VARIABLE_SECRET1
  - ENV_VARIABLE_SECRET2
  - /app/secret-file3.txt # single file mount, useful in case we mount to application existing internal folder
  - /app/secret1/: # folder with its files to mount to main container, the secret key in secret manager corresponds to pattern "$folder/$file"
      - file1.txt
      - file2.txt
  - /app/secret2/:
      - file1.txt
      - file2.txt

service:
  enabled: true
  type: ClusterIP

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 99

pdb:
  enabled: true
  minAvailable: 1

readinessProbe:
  initialDelaySeconds: 5
  failureThreshold: 1
  httpGet:
    path: /health
    port: http
livenessProbe:
  initialDelaySeconds: 5
  failureThreshold: 3
  httpGet:
    path: /health
    port: http
resources:
  requests:
    cpu: 100m

setIngressClassByField: true
ingress:
  enabled: true
  class: nginx
  hosts:
    - host: with-config-as-mounted-volume.localhost
      paths:
        - path: "/ping"
