# helm diff upgrade --install -n localhost with-config-as-mounted-volume ./charts/base/ -f ./examples/base/with-config-as-mounted-volume.yaml

image:
  repository: mendhak/http-https-echo
  tag: 34

containerPort: 8080

configs:
  ENV_VARIABLE_CONFIG: "8" # standard env variable
  /app/config1/: # folder with its files to mount to main container
    file-config1.txt: |
      file multi 
      line content 11
    file-config2.txt: |
      file multi 
      line content 12
  /app/config2/:
    file-config1.txt: |
      file multi 
      line content 21
    file-config2.txt: |
      file multi 
      line content 22

service:
  enabled: true
  type: ClusterIP

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 99

pdb:
  enabled: true
  minAvailable: 1

readinessProbe:
  initialDelaySeconds: 5
  failureThreshold: 1
  httpGet:
    path: /health
    port: http
livenessProbe:
  initialDelaySeconds: 5
  failureThreshold: 3
  httpGet:
    path: /health
    port: http
resources:
  requests:
    cpu: 100m

setIngressClassByField: true
ingress:
  enabled: true
  class: nginx
  hosts:
    - host: with-config-as-mounted-volume.localhost
      paths:
        - path: "/ping"
