{{- if .Values.dockerAuth.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "docker.auth.name" . }}"
  annotations:
    "eks.amazonaws.com/role-arn": {{ .Values.dockerAuth.serviceAccountRoleArn }}
{{- end -}}
