{{- if .Values.dockerAuth.enabled -}}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: "{{ include "docker.auth.name" . }}"
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.dockerAuth.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: "{{ include "docker.auth.name" . }}"
            namespace: {{ .Release.Namespace }}
{{- end -}}
