# helm diff upgrade --install -n localhost proxysql-basic ./charts/proxysql/ -f ./examples/proxysql/proxysql-basic.values.yaml
# helm diff upgrade --install -n localhost mysql  bitnami/mysql --set auth.rootPassword=root # install mysql
proxysql:
  podAnnotations:
    app.config/checksum: v2
  autoscaling:
    minReplicas: 1
  volumes:
    - name: proxysql-config
      mountPath: /etc/proxysql.cnf
      subPath: proxysql.cnf
      readOnly: true
      configMap:
        name: proxysql-basic
  envFrom:
    secret: proxysql-basic

  mysql:
    servers:
      - hostname: mysql.localhost
    users:
      - username: root
        password: root
