{{- $denyAll := .Values.denyAll | default (dict) -}}
{{- $istio := .Values.istio | default (dict) -}}
{{- if and (default false $denyAll.enabled) (default true $istio.enabled) }}
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: {{ include "ztm.resourceName" (dict "root" . "purpose" "service-authz-deny" "identity" "service-deny-all-authorization-policy") }}
  namespace: {{ include "ztm.workloadNamespace" . }}
  labels:
    {{- include "ztm.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ztm.denyAllPodLabels" . | nindent 6 }}
{{- end }}
