{{- $np := .Values.networkPolicy | default (dict) -}}
{{- $labels := .Values.labels | default (dict) -}}
{{- $nsr := .Values.namespaceResources | default (dict) -}}
{{- if and (default false (default .Values.namespaceResourcesEnabled $nsr.enabled)) (default true $np.enabled) (default true $np.allowDns) }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ztm.fullname" . }}-allow-dns-egress
  namespace: {{ include "ztm.workloadNamespace" . }}
  labels:
    {{- include "ztm.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes:
    - Egress
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              {{ default "kubernetes.io/metadata.name" $labels.namespaceLabelKey }}: {{ default "kube-system" $np.dnsNamespace }}
          podSelector:
            matchLabels:
              {{- toYaml (default (dict "k8s-app" "kube-dns") $np.dnsPodLabels) | nindent 14 }}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP
{{- end }}
