{{- $denyAll := default (.Values.serviceDenyAll | default (dict)) .Values.denyAll -}}
{{- $np := .Values.networkPolicy | default (dict) -}}
{{- $labels := .Values.labels | default (dict) -}}
{{- $ingress := concat (.Values.ingress | default (list)) (.Values.allowFrom | default (list)) -}}
{{- range (.Values.allowPolicies | default (list)) -}}
{{- if eq (default "" .type) "ingress" -}}
{{- $ingress = append $ingress . -}}
{{- end -}}
{{- end -}}
{{- range (.Values.allowpolices | default (list)) -}}
{{- if eq (default "" .type) "ingress" -}}
{{- $ingress = append $ingress . -}}
{{- end -}}
{{- end -}}
{{- if and (default false $denyAll.enabled) (default true $np.enabled) $ingress }}
{{- $targetNamespace := include "ztm.workloadNamespace" . -}}
{{- $targetWorkload := include "ztm.workloadName" . -}}
{{- range $ingress }}
{{- $sourceWorkload := required "ingress[].service is required" (default .workload .service) -}}
{{- $sourceNamespace := default $targetNamespace .namespace -}}
{{- $ruleName := printf "%s-ingress-from-%s-%v" $targetWorkload $sourceWorkload (.port | default 80) -}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-{{ include "ztm.sanitizeName" $ruleName }}
  namespace: {{ $targetNamespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "ztm.serviceDenyAllPodLabels" $ | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        {{- if .sourceIpBlocks }}
        {{- range .sourceIpBlocks }}
        - ipBlock:
            cidr: {{ . | quote }}
        {{- end }}
        {{- else }}
        - namespaceSelector:
            matchLabels:
              {{ default "kubernetes.io/metadata.name" $labels.namespaceLabelKey }}: {{ $sourceNamespace }}
          podSelector:
            matchLabels:
              {{- include "ztm.sourcePodLabels" . | nindent 14 }}
        {{- end }}
      ports:
        - port: {{ .port | default 80 }}
          protocol: {{ .protocol | default "TCP" }}
{{ end }}
{{- end }}
