{{- if .Values.createNginxCustomMetricTemplates -}}
apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: request-success-rate-nginx-custom
spec:
  provider:
    {{- toYaml .Values.provider | nindent 4 }}
  query: |
    sum(
      rate(
        nginx_ingress_controller_requests{
          exported_namespace="{{ "{{" }} namespace {{ "}}" }}",
          ingress="{{ "{{" }} ingress {{ "}}" }}",
          canary!="",
          status!~"5.*"
        }[{{ "{{" }} interval {{ "}}" }}]
      )
    ) 
    / 
    sum(
      rate(
        nginx_ingress_controller_requests{
          exported_namespace="{{ "{{" }} namespace {{ "}}" }}",
          ingress="{{ "{{" }} ingress {{ "}}" }}",
          canary!=""
        }[{{ "{{" }} interval {{ "}}" }}]
      )
    ) 
    * 100
---
apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: request-duration-nginx-custom
spec:
  provider:
    {{- toYaml .Values.provider | nindent 4 }}
  query: |
    sum(
      rate(
        nginx_ingress_controller_response_duration_seconds_sum{
          exported_namespace="{{ "{{" }} namespace {{ "}}" }}",
          ingress="{{ "{{" }} ingress {{ "}}" }}",
          canary!=""
        }[{{ "{{" }} interval {{ "}}" }}]
      )
    ) 
    / 
    sum(
      rate(
        nginx_ingress_controller_response_duration_seconds_count{
          exported_namespace="{{ "{{" }} namespace {{ "}}" }}",
          ingress="{{ "{{" }} ingress {{ "}}" }}",
          canary!=""
        }[{{ "{{" }} interval {{ "}}" }}]
      )
    ) 
    * 1000
{{- end }}
