{{- range $name, $ec2NodeClassSpec := .Values.ec2NodeClasses }}
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: {{ $name }}
spec:
  {{- toYaml $ec2NodeClassSpec | nindent 2 }}
{{- end }}
