apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-event-exporter-enricher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-event-exporter-enricher-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: ServiceAccount
  name: kubernetes-event-exporter-enricher
  namespace: {{ .Release.Namespace }}
  