apiVersion: v1
kind: Service
metadata:
  name: kubernetes-event-exporter-enricher
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: kubernetes-event-exporter-enricher