apiVersion: v1
kind: Service
metadata:
  name: kubernetes-event-exporter-enricher
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.enricher.port }}
      targetPort: {{ .Values.enricher.port }}
  selector:
    app: kubernetes-event-exporter-enricher