# helm diff upgrade --install -n default basic-cronjob ./charts/base-cronjob -f ./examples/base-cronjob/basic-cronjob.yaml

jobs:
  - name: basic-cronjob
    schedule: "* * * * *"
    concurrencyPolicy: Forbid
    startingDeadlineSeconds: 60
    restartPolicy: Never
    image:
      repository: nginx
      tag: latest
    command:
      - /bin/sh
      - -c
      - echo "hi" && sleep 120
