# This config allows to have shared same configs across all jobs instead of setting it fo each cronjob item
# useful for cases when we have large list of similar configs having cronjobs
default:
  image:
    registry: ""
#     repository: "repo"
#     pullPolicy: IfNotPresent
#     tag: "override"

# List of objects configuration for defining cronjobs
jobs:
  - name: cronjob1 # (required) cronjob name
    schedule: "0 * * * *" # (required) the cronjob run schedule
    image: # allows to set cronjob pod image configs, if you have default set can be optional
      registry: docker.io
      repository: busybox
      pullPolicy: IfNotPresent
      tag: latest
    command: [] # (optional)
    args: [] # (optional)

    restartPolicy: OnFailure # (optional)
    startingDeadlineSeconds: 60 # (optional)
    concurrencyPolicy: Forbid # (optional)

    serviceAccount: # (optional)
      create: true
      name: "sa-1"

    config: # (optional) allows to configure/pass config map for cronjob which items will be used as env variables in cronjob
      enabled: false
    # config:
    #   enabled: true
    #   data: "some data here"

    env: [] # optional
    # env:
    #   - name: key3
    #     value: value3
    #   - name: key4
    #     value: value4

    volumes: {} # optional
    # volumes:
    #   - name: persistent-storage
    #     mountPath: /path
    #     persistentVolumeClaim:
    #       claimName: claim

    storage: {} # optional
    # storage:
    #   - persistentVolumeClaimName: claim
    #     accessModes:
    #       - ReadWriteMany
    #     className: claim
    #     requestedSize: 5Gi
    #     enableDataSource: false

    resources: {} # optional
    # resources:
    #   request:
    #     cpu: 500m
    #     memory: 5Gi
    #   limits:
    #     cpu: 500m
    #     memory: 5Gi

    nodeSelector: {} # optional
    # nodeSelector:
    #   nodetype: "spot"

    affinity: {} # optional
    # affinity:
    #   nodeAffinity:
    #     requiredDuringSchedulingIgnoredDuringExecution:
    #       nodeSelectorTerms:
    #         - matchExpressions:
    #             - key: topology.kubernetes.io/zone
    #               operator: In
    #               values:
    #                 - antarctica-east1
    #                 - antarctica-west1

    tolerations: {} # optional
    # tolerations:
    #   - key: "example-key"
    #     operator: "Exists"
    #     effect: "NoSchedule"
