{{- $externalSecretsData := concat (fromYaml (include "base.externalSecrets" .)).data (fromYaml (include "base.extraContainersExternalSecrets" .)).data -}}
{{- if and (eq .Values.secretsDefaultEngine "ExternalSecrets") $externalSecretsData -}}
{{ $fullName := include "base.fullname" .}}

apiVersion: {{ .Values.externalSecretsApiVersion }}
kind: ExternalSecret
metadata:
  name: {{ $fullName }}
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ .Values.product }}-{{ .Values.env }}
    kind: {{ .Values.secretStoreKind | default "SecretStore" }}
  target:
    name: {{ $fullName }}
    creationPolicy: Owner
  data:
  {{- $remoteKeyBySecretKey := $.Values.externalSecretRemoteKeyBySecretKey | default dict }}
  {{- $implicitRemoteKey := print $.Values.product "/" $.Values.env "/" $fullName }}
  {{- range $secret := $externalSecretsData }}
  {{- $perSecretRemoteKey := index $remoteKeyBySecretKey $secret.secretKey }}
  - secretKey: {{ $secret.secretKey }}
    remoteRef:
      key: {{ coalesce $perSecretRemoteKey $.Values.externalSecretRemoteKey $implicitRemoteKey }}
      property: {{ $secret.property }}
  {{- end }}
{{- end }}
