apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: secret-to-be-created
    creationPolicy: Owner
  data:
  - secretKey: firstname
    remoteRef:
      key: my-json-secret
      property: pushmetrics/prod/mongo.rootpass
  - secretKey: first_friend
    remoteRef:
      key: my-json-secret2
      property: pushmetrics/prod/mongo.adminpass 
