{{- if and .Values.autoscaling.enabled (or .Values.autoscaling.trigger .Values.autoscaling.triggers) }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "base.fullname" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
  {{- with .Values.autoscaling.scaledObjectAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  scaleTargetRef:
    name: {{ include "base.fullname" . }}
  {{- if .Values.autoscaling.pollingInterval }}
  pollingInterval: {{ .Values.autoscaling.pollingInterval }}
  {{- end }}
  minReplicaCount: {{ .Values.autoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicas }}
  triggers:
    {{- if .Values.autoscaling.triggers }}
    {{- range .Values.autoscaling.triggers }}
    - type: {{ .type }}
      {{- if .metricType }}
      metricType: {{ .metricType }}
      {{- end }}
      {{- if .authenticationRef }}
      authenticationRef:
        name: {{ .authenticationRef.name }}
        kind: {{ .authenticationRef.kind | default "ClusterTriggerAuthentication" }}
      {{- end }}
      {{- if .metadata }}
      metadata:
        {{- range $key, $value := .metadata }}
        {{ $key }}: "{{ $value }}"
        {{- end }}
      {{- end }}
    {{- end }}
    {{- else }}
    - type: {{ .Values.autoscaling.trigger.type }}
      authenticationRef:
        name: {{ .Values.autoscaling.trigger.authRef | default "keda-trigger-auth-default" }}
        kind: {{ .Values.autoscaling.trigger.kind | default "ClusterTriggerAuthentication" }}
      metadata:
        {{- range $key, $value := .Values.autoscaling.trigger.metadata }}
        {{ $key }}: "{{ $value }}"
        {{- end }}
    {{- end }}
  {{- if or .Values.autoscaling.behavior .Values.autoscaling.hpaName }}
  advanced:
    horizontalPodAutoscalerConfig:
      {{- with .Values.autoscaling.hpaName }}
      name: {{ . }}
      {{- end }}
      {{- with .Values.autoscaling.behavior }}
      behavior:
{{ toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
{{- end }}
