{{- if and .Values.autoscaling.enabled .Values.autoscaling.trigger }}
{{- $triggersRaw := (coalesce .Values.autoscaling.triggers .Values.autoscaling.trigger) }}
{{- if $triggersRaw }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "base.fullname" . }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "base.fullname" . }}
  minReplicaCount:  {{ .Values.autoscaling.minReplicas }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicas }}
  triggers:
    {{- range (ternary $triggersRaw (list $triggersRaw) (kindIs "slice" $triggersRaw)) }}
    - type: {{ .type }}
      {{- if or .authRef .kind }}
      authenticationRef:
        name: {{ .authRef | default "keda-trigger-auth-default" }}
        kind: {{ .kind | default "ClusterTriggerAuthentication" }}
      {{- end }}
      metadata:
        {{- range $key, $value := .metadata }}
        {{ $key }}: "{{ $value }}"
        {{- end }}
    {{- end }}
{{- end }}
{{- end }}
