{{- if .Values.storage -}}
{{- $storageValues := (kindIs "slice" .Values.storage | ternary .Values.storage (list .Values.storage)) -}}
{{- range $storage := $storageValues }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $storage.persistentVolumeClaimName | default (include "base.fullname" $) }}
  labels:
    {{- include "base.labels" $ | nindent 4 }}
  {{- if $storage.keepPvc }}
  annotations:
    "helm.sh/resource-policy": "keep"
  {{- end }}
spec:
  accessModes:
    {{- toYaml $storage.accessModes | nindent 4 }}
  volumeMode: {{ $storage.volumeMode | default "Filesystem" }}
  resources:
    requests:
      storage: {{ $storage.requestedSize }}
  {{- if $storage.className }}
  storageClassName: {{ $storage.className }}
  {{- end }}
  {{- if $storage.enableDataSource }}
  dataSource:
    kind: PersistentVolumeClaim
    name: {{ $storage.persistentVolumeClaimName | default (include "base.fullname" $) }}
  {{- end }}
{{- end }}
{{- end }}
