{{- if .Values.rolloutStrategy.enabled -}}
{{- if eq .Values.rolloutStrategy.operator "flagger" -}}
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: {{ include "base.fullname" . }}
spec:
  provider: {{ .Values.rolloutStrategy.configs.provider | default "nginx" }}
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "base.fullname" . }}
  # ingress reference (TODO: there is supports for multiple ingresses, check and implement multiple ingress support here also )
  ingressRef:
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    name: {{ include "base.fullname" . }}
  {{- if .Values.autoscaling.enabled }}
  # HPA reference (optional)
  autoscalerRef:
    apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    name: {{ include "base.fullname" . }}
    primaryScalerReplicas:
      # min and max replicas count for primary hpa, default to main app hpa, the main app hpa values also being used for canary deploy hpa so we use this options to have custom values for primary hpa
      minReplicas: {{ .Values.rolloutStrategy.configs.primaryScalerMinReplicas | default .Values.autoscaling.minReplicas }}
      maxReplicas: {{ .Values.rolloutStrategy.configs.primaryScalerMaxReplicas | default .Values.autoscaling.maxReplicas }}
  {{- end }}
  {{- with .Values.rolloutStrategy.configs.progressDeadlineSeconds }}
  # the maximum time in seconds for the canary deployment to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: {{ . | default 600 }}
  {{- end }}
  service:
    # ClusterIP port number
    port: {{ .Values.service.port }}
    # container port number or name
    targetPort: {{ .Values.service.targetPort | default .Values.containerPort }}
  analysis:
    {{- with .Values.rolloutStrategy.configs.canaryReadyThreshold }}
    # minimum percentage of canary pods that must be ready before considering canary ready for traffic shifting (default 100)
    canaryReadyThreshold: {{ . | default 100 }}
    {{- end }}
    {{- with .Values.rolloutStrategy.configs.primaryReadyThreshold }}
    # minimum percentage of primary pods that must be ready before considering primary ready for traffic shifting (default 100)
    primaryReadyThreshold: {{ . | default 100 }}
    {{- end }}
    # schedule interval (default 60s)
    interval: {{ .Values.rolloutStrategy.configs.interval | default "60s" }}
    # max number of failed metric checks before rollback (default 10)
    threshold: {{ .Values.rolloutStrategy.configs.threshold | default 10 }}
    {{- with .Values.rolloutStrategy.configs.maxWeight }}
    # max traffic percentage (0-100) routed to canary (default 30)
    maxWeight: {{ . | default 30 }}
    {{- end }}
    {{- with .Values.rolloutStrategy.configs.stepWeight }}
    # canary increment step percentage (0-100) (default 10)
    stepWeight: {{ . | default 10 }}
    {{- end }}
    {{- with .Values.rolloutStrategy.configs.stepWeightPromotion }}
    # primary promotion increment step percentage (0-100) (default 100)
    stepWeightPromotion: {{ . | default 100 }}
    {{- end }}
    {{- with .Values.rolloutStrategy.configs.metrics }}
    # metrics checks
    metrics: {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.rolloutStrategy.configs.webhooks }}
    # testing (optional)
    webhooks:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- if .Values.rolloutStrategy.configs.alerts }}
    # custom notification/alerts (optional)
    alerts:
      {{- toYaml .Values.rolloutStrategy.configs.alerts | nindent 6 }}
    {{- end }}
    # the following config items `iterations` and `match` are being used for A/B testing configuration, so that if Flagger finds a HTTP match condition, it will ignore the maxWeight and stepWeight settings
    {{- with .Values.rolloutStrategy.configs.iterations }}
    iterations: {{ . }}
    {{- end }}
    {{- with .Values.rolloutStrategy.configs.match }}
    match: {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- with .Values.rolloutStrategy.configs.skipAnalysis }}
  # setting skipAnalysis to `true` allows deploy straight to production without the metrics and webhook checks
  skipAnalysis: {{ . | default false }}
  {{- end }}
{{- end }}
{{- end }}
