{{- if .Values.secretStore -}}
{{ $fullName := include "base.fullname" .}}
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: {{ $fullName }}
spec:
  provider:
    aws:
      service: SecretsManager
      role: {{ .Values.role }}
      region: {{ .Values.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.secretName }}
            key: access-key
          secretAccessKeySecretRef:
            name: {{ .Values.secretName }}
            key: secret-access-key
{{- end }}