# helm diff upgrade --install -n localhost http-echo-secondary ./charts/base/ -f ./examples/base/with-second-deployment/secondary-deployment-release.values.yaml

image:
  repository: mendhak/http-https-echo
  tag: 34

containerPort: 8080

service:
  enabled: false

ingress:
  enabled: false

serviceAccount:
  create: false

# have same selector annotations as main chart deployment so that main service can route incoming requests to secondary deployment pods
selectorLabelsOverride:
  app.kubernetes.io/name: http-echo-main
  app.kubernetes.io/instance: http-echo-main

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 99

readinessProbe:
  initialDelaySeconds: 5
  failureThreshold: 1
  httpGet:
    path: /health
    port: 8080
livenessProbe:
  initialDelaySeconds: 5
  failureThreshold: 3
  httpGet:
    path: /health
    port: 8080
resources:
  requests:
    cpu: 6m
