{{- range $job := .Values.jobs }}
{{- $registry := $job.image.registry }}
{{- $tag := $job.image.tag }}
{{- $image := print $registry "/" $job.image.repository ":" $tag }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $job.name | quote}}
  {{- if $job.labels }}
  labels:
    {{- range $key, $value := $job.labels }}
    {{ $value.name }}: {{ $value.value | quote}}
    {{- end }}
    app-name: {{ $job.name | quote}}
  {{- end }}
spec:
  schedule: {{ $job.schedule | quote}}
  concurrencyPolicy: {{ $job.concurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        metadata:
          {{- if $job.labels }}
          labels:
            {{- range $key, $value := $job.labels }}
            {{ $value.name }}: {{ $value.value | quote}}
            {{- end }}
            app-name: {{ $job.name | quote}}
          {{- end }}
          annotations:
            configmap: "{{ $job.config | toYaml | sha256sum | trunc 8 }}"
        spec:
          serviceAccountName: {{ $job.serviceAccount.name }}
          {{- with $job.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: {{ $job.restartPolicy }}
          containers:
            - name: {{ $job.name | quote }}
              image: {{ $image | quote}}
              imagePullPolicy: IfNotPresent
              {{- if $job.command }}
              command:
                {{- range $cmd := $job.command }}
                - {{ $cmd }}
                {{- end }}
              {{- end }}
              {{- if $job.args }}
              args:
                {{- range $args := $job.args }}
                - {{ $args }}
                {{- end }}
              {{- end }}
              {{ if $job.resources }}
              resources:
                requests:
                  cpu: {{ $job.resources.requests.cpu }}
                  memory: {{ $job.resources.requests.memory }}
                limits:
                  cpu: {{ $job.resources.limits.cpu }}
                  memory: {{ $job.resources.limits.memory }}
              {{ end }}
              env:
              {{- range $env := $job.env }}
                - name: {{ $env.name | quote}}
                  value: {{ $env.value | quote }}
              {{- end }}
              envFrom:
                - configMapRef:
                    name: {{ $job.name | quote}}
              {{- with $job.envFrom }}
                {{- toYaml . | nindent 16 }}
              {{- end }}
              volumeMounts:
            {{- range $index, $element := $job.volumes }}
                - name: {{ coalesce $element.name (add $index 1) }}
                  mountPath: {{ $element.mountPath }}
                  readOnly: {{ $element.readOnly | default false }}
            {{- end }}
          {{- with $job.nodeSelector }}
          nodeSelector:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with $job.affinity }}
          affinity:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{- with $job.tolerations }}
          tolerations:
{{ toYaml . | indent 12 }}
          {{- end }}
      {{- if $job.volumes }}
          volumes:
        {{- range $index, $element := $job.volumes }}
            - name: {{ coalesce $element.name (add $index 1) }}
          {{- if $element.persistentVolumeClaim }}
              persistentVolumeClaim:
            {{- if $element.persistentVolumeClaim.claimName }}
                claimName: {{ $element.persistentVolumeClaim.claimName }}
            {{- end }}
          {{- end }}
            {{- if $element.configMap }}
              configMap:
                name: {{ $element.configMap.name | default $job.name}}
            {{- if $element.configMap.defaultMode }}
                defaultMode: {{ $element.configMap.defaultMode }}
            {{- end }}
            {{- end }}
          {{- end }}
{{- end }}
{{- end }}
---
