{{- range $job := .Values.jobs }}
{{- if and ($job.rbac) ($job.rbac.create) }}
{{- if not (($job.serviceAccount).create) }}
{{- fail (printf "jobs[%s].serviceAccount.create must be true when jobs[%s].rbac.create is true" $job.name $job.name) }}
{{- end }}
{{- $serviceAccountName := required (printf "jobs[%s].serviceAccount.name is required when jobs[%s].rbac.create is true" $job.name $job.name) ($job.serviceAccount).name }}
{{- $rbacName := default (printf "%s-role" $job.name) $job.rbac.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ ternary "ClusterRole" "Role" (default false $job.rbac.clusterWide) }}
metadata:
  name: {{ $rbacName | quote }}
rules:
{{- toYaml $job.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ ternary "ClusterRoleBinding" "RoleBinding" (default false $job.rbac.clusterWide) }}
metadata:
  name: {{ printf "%s-binding" $rbacName | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ ternary "ClusterRole" "Role" (default false $job.rbac.clusterWide) }}
  name: {{ $rbacName | quote }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccountName | quote }}
    namespace: {{ $.Release.Namespace | quote }}
{{- end }}
{{- end }}
